# Generated by Django 3.2.8 on 2021-12-21 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='statud',
            new_name='status',
        ),
    ]
